package model;

import java.io.Serial;
import java.io.Serializable;

/**
 * Represents a player profile in the game.
 * Contains nickname, avatar, game statistics, and score.
 * Implements {@link Serializable}.
 */
public class Profile implements Serializable {
	@Serial
	private static final long serialVersionUID = 553753120546598912L;
	
	/** The player's nickname */
	private final String nickname;
	
	/** The player's avatar */
	private Avatar avatar;
	
	/** Number of hands won */
	private int handsWon;
	
	/** Number of hands lost */
	private int handsLost;
	
	 /** Number of hands that ended in a tie */
	private int handsPush;
	
	/** Number of blackjacks obtained */
	private int handsBJ;
	
	/** The player's total score */
	private int score;
	
	/**
     * Creates a new profile with the specified nickname and avatar.
     *
     * @param nickname the player's nickname
     * @param avatar the player's avatar
     */
	public Profile(String nickname, Avatar avatar) {
		this.nickname = nickname;
		this.avatar = avatar;
		if (nickname.equals("Dealer"))
			score = 0;
		else
			score = 100;
	}
	
	/** Returns the player's avatar */
	public Avatar getAvatar() {
		return avatar;
	}
	
	/** Sets the player's avatar */
	public void setAvatar(Avatar avatar) {
		if (avatar != null)
			this.avatar = avatar;
	}
	
	/** Returns the player's nickname */
	public String getNickname() {
		return nickname;
	}
	
	/** Returns the total number of hands played */
	public int getPlayed() {
		return handsWon+handsLost+handsPush;
	}
	
	/** Returns the number of hands won */
	public int getWon() {
		return handsWon;
	}
	
	/** Returns the number of hands lost */
	public int getLost() {
		return handsLost;
	}
	
	/** Returns the number of hands that ended in a tie */
	public int getPush() {
		return handsPush;
	}
	
	/** Returns the number of blackjacks obtained */
	public int getBJ() {
		return handsBJ;
	}
	
	/** Returns the player's total score */
	public int getScore() {
		return score;
	}
	
	/**
     * Updates statistics and score when the player wins a hand.
     *
     * @param bet the bet won
     */
	public void won(int bet) {
		handsWon++;
		score += bet;
	}
	
	/** Updates statistics when the hand ends in a tie */
	public void push() {
		handsPush++;
	}
	
	/**
     * Updates statistics and score when the player loses a hand.
     * If score reaches 0 and the player is not the Dealer, score is reset to 100.
     *
     * @param bet the bet lost
     */
	public void lost(int bet) {
		handsLost++;
		score -= bet;
		if (score == 0 && !nickname.equals("Dealer"))
			score = 100;
	}
	
	/**
     * Updates statistics and score when the player hits a blackjack.
     *
     * @param bet the bet won
     */
	public void blackJack(int bet) {
		handsWon++;
		handsBJ++;
		score += bet;
	}
	
	/**
     * Parses a profile from a structured string previously generated by {@link #toString()}.
     *
     * @param profileString the string to parse
     * @return a Profile object, or null if the string format is invalid
     */
	public static Profile castFromString(String profileString) {
		try {
			if (!profileString.contains("Profile{")) return null;
			String nickname = profileString.split("nickname=\'")[1].split("\'")[0];
			String avatar = profileString.split("avatar=")[1].split(",")[0];
			String handsWon = profileString.split("handsWon=")[1].split(",")[0];
			String handsLost = profileString.split("handsLost=")[1].split(",")[0];
			String handsPush = profileString.split("handsPush=")[1].split(",")[0];
			String handsBJ = profileString.split("handsBJ=")[1].split(",")[0];
			String score = profileString.split("score=")[1].split("}")[0];
			Profile profile = new Profile(nickname, Avatar.fromString(avatar));
			profile.handsWon = Integer.parseInt(handsWon);
			profile.handsLost = Integer.parseInt(handsLost);
			profile.handsPush = Integer.parseInt(handsPush);
			profile.handsBJ = Integer.parseInt(handsBJ);
			profile.score = Integer.parseInt(score);
			return profile;
		} catch (NullPointerException ignore) {
		} catch (ArrayIndexOutOfBoundsException ignore) {
			System.err.println("Wrong format");
		}
		return null;
	}
	
	/**
	 * Returns a string representation of the object, which includes: nickname, avatar handsWon, handLost, handsPush,
	 * handsBJ, score.
	 */
	@Override
	public String toString() {
		return "Profile{" +
		"nickname='" + nickname + '\'' +
		", avatar=" + avatar +
		", handsWon=" + handsWon +
		", handsLost=" + handsLost +
		", handsPush=" + handsPush +
		", handsBJ=" + handsBJ +
		", score=" + score +
		'}';
	}
}